apiVersion: v1
kind: Pod
metadata:
  labels:
    run: alexandre
    service: webserver
  name: alexandre
spec:
  containers:
  - image: nginx
    name: nginx
  - image: busybox
    name: busybox
    args:
    - sleep
    - "600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always