apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: seiya
  name: seiya
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: seiya
  type: NodePort
status:
  loadBalancer: {}
