apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: gohan
  name: gohan
spec:
  containers:
  - image: nginx
    name: gohan
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
