apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
      app: myapp
      type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
          app: myapp
          type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 20
  selector:
    matchLabels:
      type: front-end



# kubectl replace -f replicaset-definition.yml
# kubectl scale --replicas=6 -f replicaset-definition.yml
# kubectl scale --replicas=6 replicaset myapp-replicaset



